# Site settings
title: shea molloy
email: hello@sheamolloy.info
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:
url:  # the base hostname & protocol for your site
twitter_username: papermashea
github_username:  papermashea

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/home/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  work:
    output: true
    permalink: /work/:path/


