# Site settings
title: sheamolloy.info
email: hello@sheamolloy.info
description: > # this means to ignore newlines until "baseurl:"
baseurl:
url:  # the base hostname & protocol for your site
twitter_username: papermashea
github_username:  papermashea

# Build settings
markdown: kramdown
highlighter: rouge
# plugins:
#   - jekyll-seo-tag

# Pagination
# paginate: 15
# paginate_path: "/home/page:num/"

# Include nested pages
include: 
  - _filtered
relative_permalinks: false

# Collections
collections:
  portfolio:
    output: true
    tags: true
    permalink: /projects/:path/